### ISSUE TITLE
Rename Repository to polars_id_standards

### ISSUE THREAD

**Issue by ctdunc** [abstractqqq/polars_i_standards#1]
While it's still early! I think this might just be a typo.

**Comment by abstractqqq** [comment]
This is kind of stylistic...

I meant it to read like iPhone, where the i make it sound better lolol, and also i can stand for id. It's up to discussion though. What do you think? The package name can be iStandard or something lol

**Comment by ctdunc** [comment]
If we mean to implement URL & other parsers which are not strictly related to identifiers, maybe it could be like polars_xstr, as in "e**xtr**a stuff you can do with **str**ings". Similar to polars_xdt, & then we can have web, finance, etc. subpackages

**Comment by abstractqqq** [comment]
I like the xStr suggestion (similarly I like iStr lol). One thing though: I see string parsing as not limited to dataframe. A lot of folks in the polars discord need parsing in dataframe context, but I can also see a lot of use cases for Iban/URL/any kind of id-str parsing in a normal web front/back end context. 

It is not hard to expose the underlying packages to the user in Python, and in addition we are doing the data processing folks a favor by making them in-dataframe. 

I still haven't defined the scope of the project yet. But at least I think it's a good idea to be a little more ambitious at first

**Comment by ctdunc** [comment]
booo "xstr" being taken. FWIW the [source](https://github.com/Donny-GUI/xstr) appears to no longer exist, so we could probably ask to take the name. I also like iStr. If we go the route of exposing all these parsing crates to the end user, we could also do "strs" like "str" and "rs". 

as far as exposing the underlying package: its definitely possible, although it sort of negates the benefits of doing iterations on the rust side if python users are processing individual strings. My vote is for polars-xstr, that way it's consistent with polars-xdt & lines up well with the plugin ecosystem being built out (probably good for discoverability).

**Comment by abstractqqq** [comment]
Maybe a better way is to 1. first build a product that provides these functionalities for Polars and 2. open it up and ask the users if the additional, outside-of-dataframe processing is needed... Ok now we need to decide on a name

**Comment by abstractqqq** [comment]
I am proposing polars-istr... The reason I think xstr is not as good is that xstr makes people think about extra string stuff, which includes things like string distance, or even some NLP stuff, which isn't the purpose of the package and is a little too "extreme" of a name... iStr sounds friendly and stands for Identifiers Strings.

**Comment by ctdunc** [comment]
This seems reasonable to me. I am sold
